<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */


remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'custom_genesis_standard_loop' );

remove_action( 'genesis_after_content', 'genesis_get_sidebar' );


function custom_genesis_standard_loop() {

	//* Use old loop hook structure if not supporting HTML5
	if ( ! genesis_html5() ) {
		genesis_legacy_loop();
		return;
	}

	if ( have_posts() ) :

		do_action( 'genesis_before_while' );
		while ( have_posts() ) : the_post();

			do_action( 'genesis_before_entry' );

			printf( '<section class="subpage-container"><div class="wrap">' );

					printf( '<article %s>', genesis_attr( 'entry' ) );

							do_action( 'genesis_before_entry_content' );

								printf( '<div %s>', genesis_attr( 'entry-content' ) );
									do_action( 'genesis_entry_content' );
								printf( '</div>' );

								do_action( 'genesis_after_entry_content' );

								do_action( 'genesis_entry_footer' );

					printf( '</article>' );

			printf( '</div></section>' );

			do_action( 'genesis_after_entry' );

		endwhile; //* end of one post
		do_action( 'genesis_after_endwhile' );

		dynamic_sidebar( 'footer-banner-widget' ); 

	else : //* if no posts exist
		do_action( 'genesis_loop_else' );
	endif; //* end loop

}
//* Remove edit link
add_filter( 'genesis_edit_post_link' , '__return_false' );
genesis();