<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

remove_action( 'genesis_loop', 'genesis_do_loop' );
remove_action( 'genesis_loop', 'genesis_standard_loop' );

remove_action( 'genesis_after_content', 'genesis_get_sidebar' );

// Custom Loop for Blog
add_action( 'genesis_loop', 'custom_single' );
function custom_single() { 
global $default_bg;

	//* Use old loop hook structure if not supporting HTML5
	if ( ! genesis_html5() ) {
		genesis_legacy_loop();
		return;
	}

	if ( have_posts() ) :

	do_action( 'genesis_before_while' );

	printf( '<section class="subpage-container"><div class="wrap">' );
			
			printf( '<article %s>', genesis_attr( 'entry' ) );

			printf('<div class="three-fourths first">');

			while ( have_posts() ) : the_post();

				do_action( 'genesis_before_entry' );

						do_action( 'genesis_entry_header' );

							do_action( 'genesis_before_entry_content' );

								printf( '<div %s>', genesis_attr( 'entry-content' ) );
								do_action( 'genesis_entry_content' );
								echo '</div>';

							do_action( 'genesis_after_entry_content' );
						
						do_action( 'genesis_entry_footer' );

				do_action( 'genesis_after_entry' );

			endwhile; //* end of one post
			
			do_action( 'genesis_after_endwhile' );

			echo '</div>';	

			printf('<div class="one-fourth sidebar sidebar-alt widget-area">');

				dynamic_sidebar('blog-sidebar');

			printf('</div">');
	
			echo '</article>';
	
	printf( '</div></section>' ); ?>

	<?php
	echo '<div class="clear"></div>';

	else : //* if no posts exist
		do_action( 'genesis_loop_else' );
	endif; //* end loop
}

//* Run the Genesis loop
genesis();