<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

remove_action( 'genesis_loop', 'genesis_do_loop' );
remove_action( 'genesis_loop', 'genesis_standard_loop' );

remove_action( 'genesis_after_content', 'genesis_get_sidebar' );

// Custom Loop for Blog
add_action( 'genesis_loop', 'custom_single' );
function custom_single() { 

	global $default_bg;

	//* Use old loop hook structure if not supporting HTML5
	if ( ! genesis_html5() ) {
		genesis_legacy_loop();
		return;
	}

	if ( have_posts() ) : do_action( 'genesis_before_while' ); $blog_ID = get_the_ID(); ?>

		<section class="lotg-post-title">
			<div class="wrap">
				<?php do_action( 'genesis_entry_header' ); 

				do_action( 'genesis_entry_footer' );

				if ( has_post_thumbnail() ) $feat_img = wp_get_attachment_url( get_post_thumbnail_id( $blog_ID ) ); 
	            else $feat_img = get_stylesheet_directory_uri() . '/images/placeholder.png';  ?>

	            <div class="feat-img" style="background-image: url(<?php echo $feat_img ?>)"></div>
			</div>
		</section>

		<section class="subpage-container">
				
			<?php printf( '<article %s>', genesis_attr( 'entry' ) );

				while ( have_posts() ) : the_post();

					do_action( 'genesis_before_entry' );

						do_action( 'genesis_before_entry_content' );

							printf( '<div %s>', genesis_attr( 'entry-content' ) );
								do_action( 'genesis_entry_content' );

							echo '</div>';

						do_action( 'genesis_after_entry_content' );
							
					do_action( 'genesis_after_entry' ); ?>
	

				<?php endwhile; //* end of one post 
				
				do_action( 'genesis_after_endwhile' ); ?>

			</article>
		
			<ul class="share-buttons theiaStickySidebar">
				<li>
					<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo get_permalink() ?>&quote=<?php the_title() ?>" title="Share on Facebook" target="_blank">
						<img alt="Share on Facebook" src="<?php echo get_stylesheet_directory_uri() ?>/images/Facebook.svg" />
					</a>
				</li>
				<li>
					<a href="https://twitter.com/intent/tweet?source=<?php echo get_permalink() ?>&text=<?php the_title() ?>:%20<?php echo get_permalink() ?>" target="_blank" title="Tweet">
						<img alt="Tweet" src="<?php echo get_stylesheet_directory_uri() ?>/images/Twitter.svg" />
					</a>
				</li>
				<li>
					<a href="https://plus.google.com/share?url=<?php echo get_permalink() ?>" target="_blank" title="Share on Google+">
						<img alt="Share on Google+" src="<?php echo get_stylesheet_directory_uri() ?>/images/Google+.svg" />
					</a>
				</li>
				<li>
					<a href="http://pinterest.com/pin/create/button/?url=<?php echo get_permalink() ?>&description=<?php the_title() ?>" target="_blank" title="Pin it">
						<img alt="Pin it" src="<?php echo get_stylesheet_directory_uri() ?>/images/Pinterest.svg" />
					</a>
				</li>
				<li>
					<a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo get_permalink() ?>&title=<?php the_title() ?>&summary=<?php the_title() ?>&source=<?php echo get_permalink() ?>" target="_blank" title="Share on LinkedIn">
						<img alt="Share on LinkedIn" src="<?php echo get_stylesheet_directory_uri() ?>/images/LinkedIn.svg" />
					</a>
				</li>
			</ul>
		</section>

		<section class="lotg-related-posts">
			<div class="wrap">
				<?php $args = array(
					'post_type' => 'post',
					'posts_per_page' => 3,
					'post__not_in' => array( $blog_ID ),
					'orderby' => 'rand',
	    			'order' => 'ASC'
				); 
				$loop = new WP_Query( $args ); if ( $loop->have_posts() ) : ?>
					<div class="row">

						<?php while ( $loop->have_posts() ) : $loop->the_post();
							$rel_id = get_the_ID();
							if ( has_post_thumbnail() ) $rel_img = wp_get_attachment_url( get_post_thumbnail_id( $rel_id ) );
							else $rel_img = get_stylesheet_directory_uri() . '/images/placeholder.png'; ?>

							<div class="one-third">
								<a href="<?php the_permalink() ?>" title="<?php the_title() ?>">
									<h4><?php the_title() ?></h4>

									<div class="rel-img" style="background-image: url(<?php echo $rel_img ?>)"></div>

									<div class="posted"><em>Posted</em> <?php the_date() ?></div>
								</a>
							</div>
						<?php endwhile; wp_reset_query(); ?>

					</div>

					<a href="<?php echo site_url('/blog') ?>" class="btn-back-to-blog"><i class="fa fa-chevron-circle-right"></i> Back To Blog</a>
				<?php endif;?>	
			</div>
		</section>

		<?php echo do_shortcode('[fl_builder_insert_layout id="9176"]');//teach music lessons section
		echo do_shortcode('[fl_builder_insert_layout slug="schedule-your-risk-free-lesson-today"]'); 
	
	endif; //* end loop
}

//* Run the Genesis loop
genesis(); 